#include "src/game/envfx_snow.h"

const GeoLayout castle_inside_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Carpet_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2889, -282, -20, castle_inside_dl_Cube_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2206, -282, 985, castle_inside_dl_Cube_001_mesh_layer_1),
		GEO_ASM(PAINTING_ID(0x0, 1), geo_painting_draw),
		GEO_ASM(0, geo_painting_update),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Inside_Castel_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Inside_Castel_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Inside_Castel_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Inside_Castel_003_mesh_layer_1),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -2149, -276, 0, 0, 0, -90),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1513, -276, 0, 0, 0, -90, castle_inside_dl_Paintinf_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -1014, 45, -300, castle_inside_dl_Wate_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_CLOSE, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_inside_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
