extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_Tree_Leaves_A_ci8[];
extern u8 bob_dl_Tree_Leaves_A_pal_rgba16[];
extern u8 bob_dl_Bricks_Red_ci8[];
extern u8 bob_dl_Bricks_Red_pal_rgba16[];
extern u8 bob_dl_brick_overlay_rgba16[];
extern u8 bob_dl_jrb_textures_00000_rgba16_ci8[];
extern u8 bob_dl_jrb_textures_00000_rgba16_pal_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[46];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[18];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[60];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_001_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Plane_001_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Plane_001_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_001_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001_layer1_area1[];
extern Gfx mat_bob_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_bob_dl_f3dlite_material_003_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003_layer1_area1[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_5[];
