extern const GeoLayout ssk_yellow_coin_000_switch_opt1[];
extern const GeoLayout ssk_yellow_coin_000_switch_opt2[];
extern const GeoLayout ssk_yellow_coin_000_switch_opt3[];
extern const GeoLayout ssk_yellow_coin_000_switch_opt4[];
extern const GeoLayout ssk_yellow_coin_000_switch_opt5[];
extern const GeoLayout ssk_yellow_coin_000_switch_opt6[];
extern const GeoLayout ssk_yellow_coin_000_switch_opt7[];
extern const GeoLayout ssk_yellow_coin_geo[];
extern const GeoLayout ssk_yellow_coin_no_shadow_geo[];
extern u8 ssk_yellow_coin_coin1_rgba16[];
extern u8 ssk_yellow_coin_coin2_rgba16[];
extern u8 ssk_yellow_coin_coin3_rgba16[];
extern u8 ssk_yellow_coin_coin4_rgba16[];
extern Vtx ssk_yellow_coin_000_displaylist_mesh_layer_4_vtx_0[4];
extern Gfx ssk_yellow_coin_000_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_ssk_yellow_coin_YCoin1[];
extern Gfx mat_revert_ssk_yellow_coin_YCoin1[];
extern Gfx mat_ssk_yellow_coin_YCoin2[];
extern Gfx mat_revert_ssk_yellow_coin_YCoin2[];
extern Gfx mat_ssk_yellow_coin_YCoin3[];
extern Gfx mat_revert_ssk_yellow_coin_YCoin3[];
extern Gfx mat_ssk_yellow_coin_YCoin4[];
extern Gfx mat_revert_ssk_yellow_coin_YCoin4[];
extern Gfx ssk_yellow_coin_000_displaylist_mesh_layer_4[];
extern Gfx ssk_yellow_coin_000_displaylist_mesh_layer_4_mat_override_YCoin1_0[];
extern Gfx ssk_yellow_coin_000_displaylist_mesh_layer_4_mat_override_YCoin2_1[];
extern Gfx ssk_yellow_coin_000_displaylist_mesh_layer_4_mat_override_YCoin3_2[];
extern Gfx ssk_yellow_coin_000_displaylist_mesh_layer_4_mat_override_YCoin4_3[];
